version: '3.8'

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
      backend3:
        condition: service_healthy
    networks:
      - backend-network
    restart: unless-stopped

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./backend", "8081"]
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8081/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
    restart: unless-stopped

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./backend", "8082"]
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8082/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
    restart: unless-stopped

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./backend", "8083"]
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8083/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
